// New audio generation pipeline (Etap 1 per docs/voicelab.md): separate
// voice_settings for words vs sentences, ffmpeg post-processing (silence
// trim + 2-pass loudness normalize + fade) on every clip, 429-type-aware
// retry, resumable JSONL checkpoint, and a correct `sentenceAudio` write-
// back (only set true for a word whose EN+PL sentence clips were actually
// confirmed in THIS run — see scripts/audio/lib/checkpoint.ts).
//
// Etap 2 (carrier-phrase + /with-timestamps cutting for word audio) is not
// implemented yet — it needs a human A/B listening decision first (see the
// plan). Word audio here is still bare-word-plus-period, just with the
// improved settings/post-processing from Etap 1.
//
// By default, a clip already present in the Netlify `audio` blob store
// (per the last `npm run audio:audit-blobs` report) is skipped, so re-
// running this doesn't re-pay for the ~985 words generated by the old
// pipeline. Pass --force to regenerate everything under the new settings
// regardless of what's already remote.
//
// Usage:
//   npm run audio:generate -- --level=1              # a whole level
//   npm run audio:generate -- --packs=t1-p001,t1-p002
//   npm run audio:generate -- --limit=20              # small default sample
//   npm run audio:generate -- --all --force

import fs from 'fs'
import path from 'path'
import { loadConfig, createLimiter, PACK_DIR, AUDIO_OUT_DIR } from './lib/config.js'
import { WORD_SETTINGS, SENTENCE_SETTINGS_EN, SENTENCE_SETTINGS_PL, PL_VOICES, EN_VOICES } from './lib/voicePresets.js'
import { ttsPlain } from './lib/elevenLabsClient.js'
import { postProcessClip } from './lib/ffmpegPost.js'
import { checkDuration } from './lib/validate.js'
import { Checkpoint, textHash } from './lib/checkpoint.js'
import { ClipTask, Pack } from './lib/types.js'

function withPeriod(text: string): string {
  return /[.!?;]$/.test(text.trim()) ? text : text.trim() + '.'
}

function main() {
  const config = loadConfig()
  console.log(`Config: concurrency=${config.concurrency} force=${config.force} dryRun=${config.dryRun}`)

  let missingRemote: Set<string> | null = null
  if (config.blobAuditPath && fs.existsSync(config.blobAuditPath)) {
    const report = JSON.parse(fs.readFileSync(config.blobAuditPath, 'utf-8')) as { missing: string[] }
    missingRemote = new Set(report.missing)
    console.log(`Loaded blob audit: ${missingRemote.size} clips missing remotely (others will be skipped unless --force).`)
  } else {
    console.log('No blob audit found — will not skip anything already remote. Run npm run audio:audit-blobs first to avoid re-paying for existing clips.')
  }

  const allFiles = fs.readdirSync(PACK_DIR).filter((f) => f.endsWith('.json'))
  let packFiles = allFiles
  if (config.packIds) packFiles = packFiles.filter((f) => config.packIds!.has(f.replace('.json', '')))
  if (config.level !== undefined) {
    packFiles = packFiles.filter((f) => {
      const p = JSON.parse(fs.readFileSync(path.join(PACK_DIR, f), 'utf-8')) as Pack & { level: number }
      return p.level === config.level
    })
  }
  packFiles.sort()
  if (Number.isFinite(config.limit)) {
    // limit by WORDS, not packs — trim the pack list down to roughly that many words
    let words = 0
    const limited: string[] = []
    for (const f of packFiles) {
      const p = JSON.parse(fs.readFileSync(path.join(PACK_DIR, f), 'utf-8')) as Pack
      if (words >= config.limit) break
      limited.push(f)
      words += p.words.length
    }
    packFiles = limited
  }
  console.log(`Packs in scope: ${packFiles.length}`)

  const checkpoint = new Checkpoint(config.checkpointPath)
  const limit = createLimiter(config.concurrency)
  const tasks: ClipTask[] = []
  let wordIndex = 0

  const packsData: { file: string; pack: Pack }[] = packFiles.map((f) => ({ file: f, pack: JSON.parse(fs.readFileSync(path.join(PACK_DIR, f), 'utf-8')) }))

  for (const { pack } of packsData) {
    for (const w of pack.words) {
      const plVoice = PL_VOICES[wordIndex % PL_VOICES.length]
      const enVoice = EN_VOICES[wordIndex % EN_VOICES.length]
      wordIndex++

      tasks.push({ kind: 'en-word', packId: pack.id, wordId: w.id, text: withPeriod(w.english), voiceId: enVoice.id, voiceName: enVoice.name, outFile: w.audioWord })
      tasks.push({ kind: 'pl-word', packId: pack.id, wordId: w.id, text: withPeriod(w.polishAudio ?? w.polish), voiceId: plVoice.id, voiceName: plVoice.name, outFile: w.audioWordPl ?? `${w.id}-word-pl.mp3` })
      if (w.sentenceEn) tasks.push({ kind: 'en-sentence', packId: pack.id, wordId: w.id, text: w.sentenceEn, voiceId: enVoice.id, voiceName: enVoice.name, outFile: w.audioSentence })
      if (w.sentencePl) tasks.push({ kind: 'pl-sentence', packId: pack.id, wordId: w.id, text: w.sentencePl, voiceId: plVoice.id, voiceName: plVoice.name, outFile: w.audioSentencePl ?? `${w.id}-sentence-pl.mp3` })
    }
  }

  let scoped = tasks
  if (missingRemote && !config.force) {
    scoped = tasks.filter((t) => missingRemote!.has(`${t.packId}/${t.outFile}`))
  }
  console.log(`Total possible clips: ${tasks.length} | in scope after remote-skip filter: ${scoped.length}`)

  if (config.dryRun) {
    console.log('Dry run — not generating. Sample of scoped tasks:')
    scoped.slice(0, 10).forEach((t) => console.log(`  [${t.kind}] ${t.packId}/${t.outFile} (${t.voiceName}): "${t.text.slice(0, 40)}"`))
    return
  }

  let done = 0, generated = 0, skippedLocal = 0, failed = 0
  const sentenceOkThisRun = new Map<string, { en?: boolean; pl?: boolean }>()

  const settingsFor = (kind: ClipTask['kind']) =>
    kind === 'en-word' || kind === 'pl-word' ? WORD_SETTINGS : kind === 'en-sentence' ? SENTENCE_SETTINGS_EN : SENTENCE_SETTINGS_PL

  const run = async () => {
    await Promise.all(scoped.map((t) => limit(async () => {
      const hash = textHash(t.text)
      const outPath = path.join(AUDIO_OUT_DIR, t.packId, t.outFile)
      try {
        if (checkpoint.has(t.wordId, t.kind, hash) && fs.existsSync(outPath)) {
          skippedLocal++
        } else {
          const result = await ttsPlain(t.text, t.voiceId, settingsFor(t.kind), outPath, `${t.kind} ${t.wordId}`)
          if (result === 'generated') {
            await postProcessClip(outPath)
            const { ok, seconds } = await checkDuration(outPath)
            if (!ok) throw new Error(`suspiciously short output (${seconds.toFixed(2)}s)`)
            generated++
          } else {
            skippedLocal++
          }
          checkpoint.append({ wordId: t.wordId, kind: t.kind, outFile: t.outFile, textHash: hash, ok: true, ts: new Date().toISOString() })
        }
        if (t.kind === 'en-sentence' || t.kind === 'pl-sentence') {
          const rec = sentenceOkThisRun.get(t.wordId) ?? {}
          if (t.kind === 'en-sentence') rec.en = true; else rec.pl = true
          sentenceOkThisRun.set(t.wordId, rec)
        }
      } catch (e) {
        failed++
        console.error(`\nFailed [${t.kind}] ${t.wordId}: ${(e as Error).message}`)
      } finally {
        done++
        process.stdout.write(`\r[${done}/${scoped.length}] generated=${generated} skipped=${skippedLocal} failed=${failed}`)
      }
    })))
  }

  run().then(() => {
    console.log(`\n\nDone. Generated: ${generated}, skipped (already up to date): ${skippedLocal}, failed: ${failed}`)

    // Write back audioWordPl/audioSentencePl filenames + sentenceAudio flag, scoped to touched packs only.
    let flaggedTrue = 0
    for (const { file, pack } of packsData) {
      let changed = false
      for (const w of pack.words as (typeof pack.words[number] & { sentenceAudio?: boolean })[]) {
        if (!w.audioWordPl) { w.audioWordPl = `${w.id}-word-pl.mp3`; changed = true }
        if (w.sentencePl && !w.audioSentencePl) { w.audioSentencePl = `${w.id}-sentence-pl.mp3`; changed = true }
        const needsEn = !!w.sentenceEn, needsPl = !!w.sentencePl
        const rec = sentenceOkThisRun.get(w.id)
        const enOk = !needsEn || rec?.en
        const plOk = !needsPl || rec?.pl
        const shouldBeTrue = (needsEn || needsPl) && enOk && plOk
        if (shouldBeTrue && !w.sentenceAudio) { w.sentenceAudio = true; changed = true; flaggedTrue++ }
      }
      if (changed) fs.writeFileSync(path.join(PACK_DIR, file), JSON.stringify(pack, null, 2) + '\n')
    }
    console.log(`sentenceAudio newly set true: ${flaggedTrue}`)
    console.log('Next: npm run upload-audio-blobs, then npm run upload-pack-blobs (pack files changed too).')
  })
}

main()
