// Emergency correction: Level 1's sentenceAudio=true flags were set by a
// presence-only check (fix-sentence-audio-flags.ts) that trusted "a file
// exists at the expected blob key" as proof of correctness. It isn't —
// that Level 1 audio was generated by an old, pre-checkpoint pipeline
// against an EARLIER DRAFT of the sentence text. The sentences were then
// rewritten wholesale in `8002a4b feat(content): final sentences for
// Lp 1-3000` — the audio was never regenerated to match. Confirmed via git
// history (comparing current text against the `3a0621e` snapshot, right
// after "audio field population for Level 1"): 1072 of 1087 flagged Level 1
// words have text that differs from what existed when their audio was
// made — e.g. "Cry" ships audio for "Don't cry, it's okay." while the
// current sentence reads "Don't cry, I'm here."
//
// Levels 2-4 are NOT affected — verified separately: all 1374 of their
// sentenceAudio=true words have a local checkpoint record whose text hash
// matches the CURRENT sentence exactly (they were flagged by
// generate-packs.ts's own hash-checked write-back, a fundamentally safer
// path than the presence-only fix).
//
// This script unsets sentenceAudio for exactly the confirmed-stale Level 1
// ids (read from a precomputed list) so the app stops playing mismatched
// audio immediately. Real fix is regenerating those 1072 words' EN+PL
// sentence audio against current text once ElevenLabs quota allows.
//
// Usage: npx tsx scripts/audio/unflag-stale-level1-sentences.ts --write

import fs from 'fs'
import path from 'path'
import { PACK_DIR } from './lib/config.js'

const WRITE = process.argv.includes('--write')
const staleIds: string[] = JSON.parse(fs.readFileSync('/tmp/confirmed-stale-level1.json', 'utf-8'))
const staleSet = new Set(staleIds)

function main() {
  const packFiles = fs.readdirSync(PACK_DIR).filter((f) => f.endsWith('.json'))
  let unflagged = 0
  const touchedIds: string[] = []
  for (const f of packFiles) {
    const packPath = path.join(PACK_DIR, f)
    const pack = JSON.parse(fs.readFileSync(packPath, 'utf-8')) as { id: string; words: { id: string; sentenceAudio?: boolean }[] }
    let changed = false
    for (const w of pack.words) {
      if (w.sentenceAudio && staleSet.has(w.id)) {
        w.sentenceAudio = false
        changed = true
        unflagged++
        touchedIds.push(w.id)
      }
    }
    if (changed && WRITE) fs.writeFileSync(packPath, JSON.stringify(pack, null, 2) + '\n')
  }
  console.log(`Stale ids to unflag: ${staleIds.length}`)
  console.log(`Actually unflagged (were true, now false): ${unflagged}`)
  if (!WRITE) console.log('\nDry run — pass --write to save changes.')
  fs.writeFileSync(path.join('audio-output/_reports', 'stale-level1-sentence-ids.json'), JSON.stringify(touchedIds, null, 2))
}

main()
